export enum Feature {
  JOB_POSTING = 'JOB_POSTING',
  EDIT_JOB = 'EDIT_JOB',
  CANDIDATE_SEARCH = 'CANDIDATE_SEARCH',
  CANDIDATE_MATCH = 'CANDIDATE_MATCH',
  AI_MATCHING = 'AI_MATCHING',
  AI_SALARY_INSIGHTS = 'AI_SALARY_INSIGHTS',
  AI_JOB_TRENDS = 'AI_JOB_TRENDS',
  AI_OTHER_TOOLS = 'AI_OTHER_TOOLS',
  APPOINTMENTS = 'APPOINTMENTS',
  SHIFT_PLANNER = 'SHIFT_PLANNER',
  MOVE_UP_JOB = 'MOVE_UP_JOB',
}
